In [1]:
import numpy as np 

In [19]:
true_means = np.array([0.2,1,10,3,5]); 

In [20]:
Q = np.zeros(5);
eps = 0.1

In [21]:
Q.argmax()

np.int64(0)

In [22]:
N = np.zeros(5);
S = np.zeros(5)

In [23]:
for _ in range(10000): 
    if np.random.uniform()<eps : 
        action = np.random.randint(low=0,high=5,size=1)[0]; 
    else : action = Q.argmax(); 
    reward = np.random.normal(loc = true_means[action]); 
    N[action]+=1; 
    S[action]+=reward; 
    Q[action] = S[action]/N[action];

In [24]:
Q

array([ 0.27301241,  1.05383397, 10.00970578,  2.97438955,  5.01294301])

In [34]:
c = 0; 
for i in range(100000): 
    c+=np.random.binomial(1,p=0.6)
print(c)

59873


In [35]:
print(c/100000)

0.59873


In [37]:
c = 0; 
for i in range(1000000): 
    c+=np.random.binomial(1,p=0.6)
print(c)

600164


In [38]:
c = 0; 
for i in range(1000000): 
    c+=np.random.binomial(1,p=0.8)
print(c)

799887


In [39]:
c = 0; 
for i in range(1000000): 
    c+=np.random.uniform()
print(c)

499629.13019133103


In [40]:
c/1000000

0.49962913019133104

In [ ]:
##### ########

In [41]:
eps = 0.15;
Q = np.zeros(3); 
S = np.zeros(3); 
N = np.zeros(3);
while 1 : 
    if eps < np.random.uniform() : action = np.random.randint(low=0,high=3,size=1)[0]; 
    else: action = Q.argmax(); 
    reward = int(input(f'Advertisement number {action+1}'));
    S[action]+=reward; 
    N[action]+=1; 
    Q[action] = S[action]/N[action];

Advertisement number 1 1
Advertisement number 1 1
Advertisement number 1 1
Advertisement number 1 0
Advertisement number 2 0
Advertisement number 2 1
Advertisement number 2 1
Advertisement number 2 0
Advertisement number 2 1
Advertisement number 2 0
Advertisement number 2 0
Advertisement number 1 0
Advertisement number 2 1
Advertisement number 1 1
Advertisement number 1 1
Advertisement number 1 1
Advertisement number 1 1
Advertisement number 3 1
Advertisement number 1 1
Advertisement number 3 1
Advertisement number 1 1
Advertisement number 3 1
Advertisement number 3 0
Advertisement number 2 1
Advertisement number 1 0
Advertisement number 3 1
Advertisement number 2 0
Advertisement number 3 1
Advertisement number 2 0
Advertisement number 1 0
Advertisement number 3 1
Advertisement number 3 1
Advertisement number 1 1
Advertisement number 3 0
Advertisement number 2 1
Advertisement number 2 1
Advertisement number 3 0
Advertisement number 1 1


KeyboardInterrupt: Interrupted by user

In [42]:
Q

array([0.73333333, 0.53846154, 0.7       ])

In [48]:
eps = 0.15;
Q = np.zeros(3); 
S = np.zeros(3); 
N = np.zeros(3);
for i in range(10000): 
    if eps < np.random.uniform() : action = np.random.randint(low=0,high=3,size=1)[0]; 
    else: action = Q.argmax(); 
    # For simulation only : 
    if action ==0 : reward = np.random.choice([0,1],p=[0.2,0.8]); 
    elif action==1 : reward = np.random.choice([0,1],p=[0.8,0.2]);
    else : reward = np.random.choice([0,1],p=[0.4,0.6]);
    S[action]+=reward; 
    N[action]+=1; 
    Q[action] = S[action]/N[action];

In [49]:
Q

array([0.79990562, 0.18285517, 0.59602649])